# Generated by Django 5.0.3 on 2026-05-30 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_systemsettings_company'),
        ('purchases', '0002_purchase_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.company'),
        ),
    ]
