# Generated by Django 5.0.3 on 2026-05-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
