# Generated by Django 5.0.3 on 2026-05-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_po_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='po_number',
        ),
    ]
