# Generated by Django 5.0.3 on 2026-05-20 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company_name', models.CharField(default='Charcoal ERP Inc.', max_length=255)),
                ('address', models.CharField(default='123 Industrial Park, Coal City, NY 10001', max_length=500)),
                ('phone_number', models.CharField(default='+1 800-COAL-ERP', max_length=50)),
                ('tax_id', models.CharField(default='27AABCU9603R1ZX', max_length=50)),
                ('currency_symbol', models.CharField(default='₹ (INR)', max_length=10)),
                ('weight_unit', models.CharField(default='Metric Tonnes (MT)', max_length=50)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
