# Generated by Django 5.0.3 on 2026-05-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='email',
            field=models.EmailField(blank=True, default='info@charcoalerp.com', max_length=255, null=True),
        ),
    ]
