# Generated by Django 5.0.3 on 2026-05-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_invoice_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
