# Generated by Django 5.0.3 on 2026-05-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_delivery_location_alter_sale_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
