# Generated by Django 5.0.3 on 2026-06-01 16:37

from django.db import migrations


def migrate_sales_to_items(apps, schema_editor):
    Sale = apps.get_model('sales', 'Sale')
    SaleItem = apps.get_model('sales', 'SaleItem')

    for sale in Sale.objects.all():
        # Clean product name to strictly match choices if possible, else default to CHARCOAL
        product_name = sale.coal_type.upper() if sale.coal_type else 'CHARCOAL'
        if 'FIREWOOD' in product_name:
            product_name = 'FIREWOOD'
        else:
            product_name = 'CHARCOAL'

        qty = sale.quantity_ton or 0
        rate = sale.rate or 0
        amount = qty * rate

        # Set subtotal on Sale header
        sale.subtotal = amount
        sale.tax = 0
        sale.save(update_fields=['subtotal', 'tax'])

        SaleItem.objects.create(
            sale=sale,
            company=sale.company,
            product=product_name,
            quantity_ton=qty,
            unit='MT',
            rate=rate,
            amount=amount
        )

def reverse_migration(apps, schema_editor):
    SaleItem = apps.get_model('sales', 'SaleItem')
    SaleItem.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale_notes_sale_payment_status_sale_subtotal_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_sales_to_items, reverse_migration),
    ]
