# Generated by Django 5.0.3 on 2026-06-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_migrate_sale_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='coal_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity_ton',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='rate',
        ),
    ]
