# Generated by Django 5.0.3 on 2026-06-04 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_systemsettings_company'),
        ('customers', '0004_customer_company'),
        ('sales', '0009_remove_sale_coal_type_remove_sale_quantity_ton_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('invoice_number', 'company'), name='unique_active_invoice_per_company'),
        ),
    ]
